### ISSUE TITLE
很多字的音会有很多读音

### ISSUE THREAD

**Issue by jxmlearner** [SummerWish/pinyinlite#6]
例如 哈尔滨 -> ta er bin
哈->['ta','ha','sha','he']
哈字应该只有声调不同吧

**Comment by breezewish** [comment]
“哈”的确有那么多拼音，详见：https://zh.wiktionary.org/zh-hans/%E5%93%88

返回所有可能的拼音是这个库的预期行为，因为它并不根据上下文猜测发音——由于地域不同，同一个词本就可能被认为是不同的发音，所以只猜测出一个最佳发音很可能会和用户输入的拼音不匹配。相反地，这个库会返回所有可能的拼音，做匹配时，只要其中某个组合匹配上即可。

**Comment by jxmlearner** [comment]
感谢回复，好吧，只好另外再去判断了^_^
